### ISSUE TITLE
ignore not working

### ISSUE THREAD

**Issue by bjorneg** [debops/ansible-libvirtd#21]
Hi

Im trying debops.libvirtd and run into a problem:

I do get an error thrown in  "Generate libvirt configuration files" - variable parameters is undefined.

If I change change "ignore" to "comment" in the variable "libvirtd__default_configuration", then it works. I also have to comment out the "unix_sock_group" stuff.

I think there is something with the template - but I cant figure it out.

BR,

/////Björne

**Comment by drybjed** [comment]
The `libvirtd__default_configuration` variable has lots of data, can you tell which `ignore` instance are you changing? Do you change all of them?

Did you define any `libvirtd__*` variables in Ansible inventory? Do you use the role with its own example playbook, or are you using your own playbook?

**Comment by bjorneg** [comment]
Hi

I ran it as it came from github - no changes, no customization. I have not define any own variables for libvirtd. I use it with the whole debops playbooks, ie I invoke "debops" from the commandline.

This is from the defaults (See my comments inline):

libvirtd__default_configuration:

###This I have to comment out
  - 'unix_sock_group':    '{{ libvirtd__unix_sock_group }}'
    'unix_sock_ro_perms': '0770'
    'unix_sock_rw_perms': '0770'

  # Ref: https://forum.opennebula.org/t/polkitd-traps-general-protection-ip-in-libmozjs-17-0-so/399/3

 ###Here I have to change 'ignore' to 'comment'
  
- name: 'auth_unix_ro'
    value: 'none'
    state: '{{ "present"
               if (libvirtd__deployment_mode == "opennebula")
               else "ignore" }}'

  # Ref: https://forum.opennebula.org/t/polkitd-traps-general-protection-ip-in-libmozjs-17-0-so/399/3

 ###Here I have to change 'ignore' to 'comment'
  
  - name: 'auth_unix_rw'
    value: 'none'
    state: '{{ "present"
               if (libvirtd__deployment_mode == "opennebula")
               else "ignore" }}'

Thanks for your quick answer.

BR,

/////Björne

**Comment by drybjed** [comment]
Hey, no need to close the issue when it's not resolved... :-)

Anyway, I tried to install `libvirtd` on Debian Stretch without any configuration, and the template is generated fine... What OS/release are you using, what Ansible version? You could copy the entire error message from Ansible here - I know that Jinja output is intimidating, but don't worry, I can deal with it.

**Comment by bjorneg** [comment]
Hi 

This is the error messgae:

TASK [debops.libvirtd : Generate libvirtd configuration files] *****************
failed: [test-amd64new] (item=etc/libvirt/libvirtd.conf) => {"failed": true, "item": "etc/libvirt/libvirtd.conf", "msg": "AnsibleUndefinedVariable: 'parameters' is undefined"}

Ansible version:
ansible 2.2.1.0

Debian version:
8.7

BR,
/////Björne

**Comment by drybjed** [comment]
OK, I think I know why that's happening - the there must be some dictionaries that the template parses with the wrong parameters. I know where to look now, I'll try to fix that issue soon.

**Comment by drybjed** [comment]
@bjorneg The bug should now be fixed. Can you update the role to the latest release and check if that helps?

**Comment by drybjed** [comment]
Closing the issue as fixed due to no communication and project consolidation to [`debops/debops`](https://github.com/debops/debops/) repository.
